version: '3.8'

services:
  # PostgreSQL service
  db:
    image: postgres:14
    container_name: postgres_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: notes_app
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Go backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: go_backend
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: notes_app
      DB_SSLMODE: disable
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
